In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1118, 7930, 4536, 2085],
 [1118, 7930, 4536, 9196],
 [1118, 2349, 4536, 2762],
 [6866, 9687, 8646, 5544, 2714],
 [6866, 9687, 8646, 5544, 553],
 [1797, 1118, 513, 4536, 194],
 [2684, 2119, 5514, 5544]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1118 7930 4536 2085]
 [   0    0    0    0 1118 7930 4536 9196]
 [   0    0    0    0 1118 2349 4536 2762]
 [   0    0    0 6866 9687 8646 5544 2714]
 [   0    0    0 6866 9687 8646 5544  553]
 [   0    0    0 1797 1118  513 4536  194]
 [   0    0    0    0 2684 2119 5514 5544]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 256ms/step


array([[[ 0.04725666, -0.04257992, -0.0370305 , -0.03282501,
         -0.04406815,  0.01069363, -0.00120378,  0.02588968,
          0.04209337,  0.01128565],
        [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501,
         -0.04406815,  0.01069363, -0.00120378,  0.02588968,
          0.04209337,  0.01128565],
        [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501,
         -0.04406815,  0.01069363, -0.00120378,  0.02588968,
          0.04209337,  0.01128565],
        [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501,
         -0.04406815,  0.01069363, -0.00120378,  0.02588968,
          0.04209337,  0.01128565],
        [-0.00231256,  0.03692773,  0.02422467, -0.01811821,
         -0.0185213 ,  0.01659815,  0.00275429, -0.013749  ,
          0.00164948,  0.03204948],
        [-0.04632524,  0.00740448,  0.0029367 , -0.0154961 ,
         -0.0437866 , -0.00290645, -0.00373131, -0.03499898,
          0.01730319, -0.03698402],
        [ 0.03789952,  0.03436235,  0.02984441, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1118, 7930, 4536, 2085])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 40ms/step


array([[ 0.04725666, -0.04257992, -0.0370305 , -0.03282501, -0.04406815,
         0.01069363, -0.00120378,  0.02588968,  0.04209337,  0.01128565],
       [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501, -0.04406815,
         0.01069363, -0.00120378,  0.02588968,  0.04209337,  0.01128565],
       [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501, -0.04406815,
         0.01069363, -0.00120378,  0.02588968,  0.04209337,  0.01128565],
       [ 0.04725666, -0.04257992, -0.0370305 , -0.03282501, -0.04406815,
         0.01069363, -0.00120378,  0.02588968,  0.04209337,  0.01128565],
       [-0.00231256,  0.03692773,  0.02422467, -0.01811821, -0.0185213 ,
         0.01659815,  0.00275429, -0.013749  ,  0.00164948,  0.03204948],
       [-0.04632524,  0.00740448,  0.0029367 , -0.0154961 , -0.0437866 ,
        -0.00290645, -0.00373131, -0.03499898,  0.01730319, -0.03698402],
       [ 0.03789952,  0.03436235,  0.02984441, -0.03163383,  0.04518375,
         0.04576975, -0.04206214,  0.03459414